// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Theo_DisableTouchUI","status":true,"description":"Removes the touch UI and reposition the menu accordingly","parameters":{}},
{"name":"Fullscreen","status":true,"description":"Starts the game in fullscreen","parameters":{}},
{"name":"SplashScreen","status":false,"description":"","parameters":{}},
{"name":"TextPicture","status":false,"description":"Displays text as a picture.","parameters":{}},
{"name":"RF_CustomWindowMessage","status":false,"description":"(v.1.0) Create custom window. View documentation for plugin commands.","parameters":{}},
{"name":"TSGamepad","status":true,"description":"[v1.0] OnScreen Controls for RMMZ","parameters":{"dpad":"1","stick":"60","exten":".svg","bcAd":"#7dc242","bcBd":"#ed1c24","bcXd":"#24bcee","bcYd":"#f0ea1b"}},
{"name":"Chain","status":true,"description":"[v1.0] Blockchain Ethers Connect for RMMZ","parameters":{}},
{"name":"PKD_DevOptions","status":false,"description":"v1.0.1 - Helpful options for developing and testing game","parameters":{"skipTitle":"true","noPlayTest":"false","console":"false","focusGame":"true","drawEventsNames":"true"}},
{"name":"SocketIO","status":false,"description":"v2.3.0 - Socket.IO (for Alpha NET Z plugin)","parameters":{}},
{"name":"Alpha_@Core","status":false,"description":"(v.0.3) Alpha Core Plugin","parameters":{}},
{"name":"Alpha_NETZ_MZ","status":false,"description":"(v.0.6)[PRO] Multiplayer for RPG Maker","parameters":{"ANETZ":"","connection:s":"{\"serverIp\":\"rootkit-multiplayer-server.herokuapp.com\",\"serverPort\":\"443\"}","spacer|gamesettings":"","gameModeSettingsGroup":"","onlySameMap:b":"false","singlePlayerAllowed:b":"true","roomFilter:b":"false","saveLoadGame:b":"true","inGameChat:b":"true","chatStartMessage":"\\}Welcome to Kronos Trigger, \\C[1]'T'\\C[6] to chat","chatOpenCloseKey":"t","chatSayKey":"t","playersSettingsGroup":"","actorsForNetwork:intA":"[\"1\",\"2\",\"3\",\"4\"]","isActorSelectionAllowed:b":"false","isSinglePlayerStartAllowed:b":"true","playerActorNameType":"Instead Nickname","playerLeaveGameCommonEvent:int":"0","globalData:s":"{\"globalVariablesIds:intA\":\"[]\",\"globalSwitchesIds:intA\":\"[]\"}"}},
{"name":"CustomChat","status":false,"description":"Custom Script","parameters":{}},
{"name":"RS_InputDialog","status":false,"description":"This plugin allows you to display Text Edit Box on the screen. <RS_InputDialog>","parameters":{"textBox Width":"488","textBox Height":"36","variable ID":"3","debug":"true","Text Hint":"Please enter the value...","direction":"ltr","Max Length":"255","Style":"","CSS":"\"\"","Button Name":"","Ok":"OK","Cancel":"Cancel","Position":"center"}}
];
